spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    contexts: dev
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: -1
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
app:
  storage:
    location: ./uploads/
