spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dealspotter
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    clear-checksums: true
    contexts: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1

  web:
    resources:
      static-locations: classpath:/static/,file:/Users/dawid/uploads/
app:
  storage:
    location: /Users/dawid/uploads/

